---
title: "Clinical manifestations of primary CoQ deficiencies"
author: "María Alcázar-Fabra & Gloria Brea-Calvo"
date: ""
output: 
  html_document: 
    fig_caption: yes
    fig_height: 4
    includes:
      in_header: header.html
    self_contained: no
    theme: cerulean
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
```


```{r}
library(dplyr)
library(assertr)
library(ggplot2)

#source("render_toc.R")
```


```{r}
#render_toc("index.Rmd", base_level = 2, toc_depth = 1)
```



```{r read.data, include=FALSE}

datos <- gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/1zCc9r7Uy_6ujOU5qXc7VOXuN4OSvIJg5Tx9iqWw6swY/edit?usp=sharing", sheetid = 1) %>%
  arrange(group)

npatients <- gsheet::gsheet2tbl("https://docs.google.com/spreadsheets/d/1zCc9r7Uy_6ujOU5qXc7VOXuN4OSvIJg5Tx9iqWw6swY/edit?usp=sharing#gid=1452337852") 

datos %>%
 # verify(ncol(.) == 12) %>%
  verify(names(datos)[1:2] == c("group", "symptom")) %>%
  verify(all.equal(names(datos)[3:ncol(datos)], names(npatients)))

npatients <- as.numeric(npatients)

```


```{r percent}
percent <- datos

for (j in 3:ncol(datos)) {
  percent[, j] <- 100*(percent[, j]/npatients[j - 2])
}

```


```{r datos.long}
datos.long <- percent %>%
  tidyr::pivot_longer(cols = 3:ncol(datos), names_to = "gene") %>%
  mutate(gene = factor(gene, levels = names(datos)[3:ncol(datos)]))
```


```{r heatmap.fun}

plotfun <- function(df = datos.long, grupo = NULL, npat = npatients) {
  
  datos.sub <- df %>%
    dplyr::filter(group == grupo) %>%
    mutate(symptom = factor(symptom, 
                            levels = sort(unique(symptom), decreasing = TRUE)))

## Sort rows by prevalence
df2 <- datos.sub %>%
  dplyr::filter(value > 0) %>%
  group_by(symptom) %>%
  summarise(n.site = sum(value)) %>%
  arrange(n.site)

datos.sub$symptom <- factor(datos.sub$symptom, levels = df2$symptom)


patients <- data.frame(gene = unique(df$gene),
                       n.pat = npat)

heatm <- ggplot(datos.sub) +
  aes(x = gene, y = symptom) +
  geom_tile(aes(fill = value), colour = "grey80",
            height = 1, width = 1) +
  #scale_fill_viridis(name = "% patients", option = "magma") +
  scale_fill_distiller(name = "% patients", type = "seq",
                       palette = "YlGnBu", direction = 1,
                       limits = c(0, 100)) +
  coord_equal(clip = "off") +
  scale_x_discrete(position = "top") +
  theme(axis.text.x.top = element_text(angle = 90, hjust = 0, vjust = 0.5)) +
  xlab("") +
  ylab("") +
  theme(plot.margin = unit(c(0, 0, 0.5, 0), "cm")) +
  theme(panel.background = element_blank()) +
  geom_text(data = patients, aes(y = 0, label = n.pat), size = 3)

heatm
  
}

```


-----------------------------------------------------------------


<br>

Aquí va texto

<br>







## {.tabset .tabset-fade .tabset-pills}


### The tool

Here you can ...

Go to table to search the data

### CSN

```{r out.width='100%', fig.height=9}
plotfun(grupo = "CSN")
```


### Heart

```{r out.width='100%'}
plotfun(grupo = "Heart")
```


### Kidney

```{r out.width='100%'}
plotfun(grupo = "Kidney")
```


### Liver

```{r out.width='100%'}
plotfun(grupo = "Liver")
```


### Lung

```{r out.width='100%'}
plotfun(grupo = "Lung")
```


### Muscle

```{r out.width='100%'}
plotfun(grupo = "Muscle")
```


### PNS/Sensory organs

```{r out.width='100%'}
plotfun(grupo = "PNS/sensory organs")
```


### Other

```{r out.width='100%'}
plotfun(grupo = "Other")
```


### Table

In this table you can search by symptom (and link to symptom description). Numbers represent number of patients

```{r out.width='100%'}
library(DT)
datatable(datos, filter = "top", rownames = FALSE)
```


## {-}

Epílogo...

Last update: `r Sys.Date()`
